#!/bin/bash

# Simple deployment script using curl and Supabase SQL Editor API
# This concatenates all migrations and sends them to Supabase

set -e

SUPABASE_URL="https://berubgvunuldigjqpcju.supabase.co"
SERVICE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJlcnViZ3Z1bnVsZGlnanFwY2p1Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NDYzMDYxNywiZXhwIjoyMDkwMjA2NjE3fQ.wecxul1cFggOTbcxGRRBxw7gIuJpVNuQAn9_VTaJnHg"

echo "🚀 ClearTalk Database Setup"
echo "=============================="
echo ""
echo "📦 Project: https://berubgvunuldigjqpcju.supabase.co"
echo ""
echo "⚠️  Manual Setup Required:"
echo ""
echo "Since automated SQL execution requires additional setup,"
echo "please follow these steps to deploy the database:"
echo ""
echo "1. Go to: https://supabase.com/dashboard/project/berubgvunuldigjqpcju/sql/new"
echo ""
echo "2. Copy and paste each migration file from ./migrations/ in order:"
echo "   - 001_users_table.sql"
echo "   - 002_conversations_table.sql"
echo "   - 003_messages_table.sql"
echo "   - 004_biff_scores_table.sql"
echo "   - 005_message_shield_logs_table.sql"
echo "   - 006_gray_rock_sessions_table.sql"
echo "   - 007_solo_mode_config_table.sql"
echo "   - 008_professional_access_table.sql"
echo "   - 009_pattern_detections_table.sql"
echo "   - 010_notifications_table.sql"
echo "   - 011_message_attachments_table.sql"
echo "   - 012_user_preferences_table.sql"
echo "   - 013_audit_log_table.sql"
echo "   - 014_rls_policies.sql"
echo ""
echo "3. Click 'Run' after pasting each file"
echo ""
echo "4. (Optional) Run seed.sql to create test data"
echo ""
echo "5. Run verify-schema.sql to verify everything works"
echo ""
echo "✅ All environment variables are configured!"
echo "   - Server: /Users/jkw/Documents/Work/Projects/ClearTalk/server/.env"
echo "   - Mobile: /Users/jkw/Documents/Work/Projects/ClearTalk/apps/mobile/.env"
echo "   - Portal: /Users/jkw/Documents/Work/Projects/ClearTalk/apps/portal/.env.local"
echo ""
